### ISSUE TITLE
Getting Started: How do I get back to the "new project" choices in BlackDiamond Studio? Sample / default data warehouse? 

### ISSUE THREAD

**Issue by TLButton** [MobilizeNet/BlackDiamondStudio#68]
I started the new version of BlackDiamond Studio and was greeted by the 4 choices for a new project, then when I chose "none" it sent me to the from scratch new project Wizard.  I would like to return to the 4 choices (connect to existing Snowflake db, migrate, etc). How do I get back there?

**Comment by jofallas** [comment]
Hi @TLButton some questions to clarify your flow: 

Once you chose the "Do not upload code." are you clicking on "Finish Setup"?

If yes, after clicking on that are you being redirected to the Project Summary Tab? 

<img width="725" alt="Project Summary" src="https://user-images.githubusercontent.com/12476691/171478292-72b00004-17bd-4b1f-93ad-8c816e6911be.png">

**Comment by TLButton** [comment]
No, I'm in the "new project" from scratch wizard.  I can't seem to navigate back to the 4 choices. 
![image](https://user-images.githubusercontent.com/99206645/171479262-66452a8a-5755-4c1c-8767-352a288ce344.png)

**Comment by jofallas** [comment]
Ok, If that happened probably was because your browser had some cache that was showing our old version of the Project Creation.

Now in this "New Project" From scratch wizard you will need to complete at least the steps [#1](https://docs.mobilize.net/bifrost-documentation-or-mobilize.net/blackdiamond-studio-documentation/bds-portal/creating-my-first-project/1.-name-project) and [#2](https://docs.mobilize.net/bifrost-documentation-or-mobilize.net/blackdiamond-studio-documentation/bds-portal/creating-my-first-project/2.-setup-repository) before being able to navigate to the last step called [**Code**](https://docs.mobilize.net/bifrost-documentation-or-mobilize.net/blackdiamond-studio-documentation/bds-portal/creating-my-first-project/4.-code-in-process), Step where you will be able to choose between our 4 project types
<img width="749" alt="Captura de Pantalla 2022-06-01 a la(s) 13 02 33" src="https://user-images.githubusercontent.com/12476691/171482165-52849a9f-7334-420f-85c0-ea5c46d5fd27.png">

**Comment by devops-bds** [comment]
The new user experience of the project wizard allow the user to navigate between steps, this is not an issue anymore.
